// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqeoowsMODtS7YE0BR9hvDn3autGhkktU',
    appId: '1:462765918244:web:bab2658ebdbc6e53d630b1',
    messagingSenderId: '462765918244',
    projectId: 'daftar-belanja-da49d',
    authDomain: 'daftar-belanja-da49d.firebaseapp.com',
    databaseURL: 'https://daftar-belanja-da49d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'daftar-belanja-da49d.firebasestorage.app',
    measurementId: 'G-X4X208T3W2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAds9PO4FA8uy_Uy1XTSakjRT047HlL16Y',
    appId: '1:462765918244:android:a056e8b15dbd9c80d630b1',
    messagingSenderId: '462765918244',
    projectId: 'daftar-belanja-da49d',
    databaseURL: 'https://daftar-belanja-da49d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'daftar-belanja-da49d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdxZlMZLxjJqiMu6ghdVzdLALwqZhhkkI',
    appId: '1:462765918244:ios:4308fc761dfde508d630b1',
    messagingSenderId: '462765918244',
    projectId: 'daftar-belanja-da49d',
    databaseURL: 'https://daftar-belanja-da49d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'daftar-belanja-da49d.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdxZlMZLxjJqiMu6ghdVzdLALwqZhhkkI',
    appId: '1:462765918244:ios:4308fc761dfde508d630b1',
    messagingSenderId: '462765918244',
    projectId: 'daftar-belanja-da49d',
    databaseURL: 'https://daftar-belanja-da49d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'daftar-belanja-da49d.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqeoowsMODtS7YE0BR9hvDn3autGhkktU',
    appId: '1:462765918244:web:1a54f20359df33cdd630b1',
    messagingSenderId: '462765918244',
    projectId: 'daftar-belanja-da49d',
    authDomain: 'daftar-belanja-da49d.firebaseapp.com',
    databaseURL: 'https://daftar-belanja-da49d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'daftar-belanja-da49d.firebasestorage.app',
    measurementId: 'G-YPQN1JS2QB',
  );
}
